services:
    article_article_event_subscriber:
        class: Biz\Article\Event\ArticleEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    content_event_subscriber:
        class: Biz\Content\Event\ContentEventSubscriber
        arguments: ['@biz']
        tags:
           - { name: codeages_plugin.event.subscriber }

    user_course_thread_event_subscriber:
        class: Biz\User\Event\CourseThreadEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_classroom_event_subscriber:
        class: Biz\User\Event\ClassroomEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_user_event_subscriber:
        class: Biz\User\Event\UserEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_vip_member_event_subscriber:
        class: Biz\User\Event\VipMemberEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    taxonomy_article_event_subscriber:
        class: Biz\Taxonomy\Event\ArticleEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    upload_file_event_subscriber:
        class: Biz\File\Event\UploadFileEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    orderrefererlog_event_subscriber:
        class: Biz\RefererLog\Event\OrderRefererLogEventSubscriber
        arguments: ['@biz']
        tags:
                - { name: codeages_plugin.event.subscriber }
    tokenbucket_event_subscriber:
        class: Biz\PostFilter\Event\TokenBucketEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    sms_task_event_subscriber:
        class: Biz\Sms\Event\TaskEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    sms_testpaper_event_subscriber:
        class: Biz\Sms\Event\TestPaperEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    sms_pay_center_event_subscriber:
        class: Biz\Sms\Event\PayCenterEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    tag_course_set_event_subscriber:
        class: Biz\Taxonomy\Event\CourseSetEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    status_event_subscriber:
        class: Biz\User\Event\StatusEventSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }

    open_course_sms_event_subscriber:
        class: Biz\Sms\Event\OpenCourseSmsEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    statement_event_subscriber:
        class: Biz\Xapi\Event\StatementEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_account_event_subscriber:
        class: Codeages\Biz\Pay\Subscriber\AccountSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    navigation_event_subscriber:
        class: Biz\Content\Event\NavigationEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    destroy_account_event_subscriber:
        class: Biz\DestroyAccount\Event\DestroyAccountEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }