admin_v2:
    name: admin_v2.basic_menu
    parent: null
    children:
        admin_v2_user:
            quick_entrance_icon_class: 'icon-color-blue'
            name: admin_v2.nav.user
            children:
                admin_v2_user_group:
                    name: admin_v2.user.user_group
                    is_group: true
                    children:
                        admin_v2_user_show:
                            quick_entrance_icon: 'user'
                            router_name: admin_v2_user
                            name: admin_v2.user.basic_menu
                            children:
                                admin_v2_user_manage:
                                    name: admin_v2.user.basic.basic_tab
                                    router_name: admin_v2_user
                                    children:
                                        admin_v2_user_create:
                                            name: admin_v2.user.basic.basic_tab.create_btn
                                            mode: modal
                                            group: topBtn
                                            visible: (user.type != 'system')
                                        admin_v2_user_edit:
                                            name: admin_v2.user.basic.basic_tab.edit_btn
                                            mode: modal
                                            group: groupButton
                                            visible: (user.type != 'system')
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_roles:
                                            name: admin_v2.user.basic.basic_tab.setting_roles_btn
                                            mode: modal
                                            group: groupButton
                                            visible: (user.type != 'system')
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_avatar:
                                            name: admin_v2.user.basic.basic_tab.update_avatar_btn
                                            mode: modal
                                            group: groupButton
                                            visible: (user.type != 'system')
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_change_password:
                                            name: admin_v2.user.basic.basic_tab.change_password_btn
                                            mode: modal
                                            group: groupButton
                                            visible: (user.type != 'system')
                                            router_params:
                                                userId: (user.id)
                                        admin_v2_user_send_passwordreset_email:
                                            name: admin_v2.user.basic.basic_tab.send_passwordreset_email_btn
                                            group: groupButton
                                            class: send-passwordreset-email
                                            mode: none
                                            visible: (user.type != 'system')
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_send_emailverify_email:
                                            name: admin_v2.user.basic.basic_tab.send_emailverify_email_btn
                                            class: send-emailverify-email
                                            group: groupButton
                                            mode: none
                                            visible: (user.type != 'system')
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_lock:
                                            name: admin_v2.user.basic.basic_tab.lock_btn
                                            group: groupButton
                                            class: lock-user
                                            mode: none
                                            visible: (user.type != 'system' and user.locked == 0)
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_unlock:
                                            name: admin_v2.user.basic.basic_tab.unlock_btn
                                            class: unlock-user
                                            group: groupButton
                                            mode: none
                                            visible: (user.type != 'system' and user.locked == 1)
                                            router_params:
                                                id: (user.id)
                                        admin_v2_user_org_update:
                                            name: admin_v2.user.basic.basic_tab.org_update_btn
                                            parent: admin_user_manage
                                            mode: modal
                                            group: groupButton
                                            visible: ( app.user.id != user.id and setting('magic.enable_org', 0) == 1 )
                                            router_params:
                                                id: (user.id)
                                            disable: true
                                admin_v2_online:
                                    name: admin.user.basic.online
                                admin_v2_login_record:
                                    name: admin.user.basic.login_record_tab
        admin_v2_system:
            quick_entrance_icon_class: 'icon-color-blue'
            name: admin_v2.nav.system
            children:
                # 通用管理
                admin_v2_general_group:
                    name: admin_v2.general.basic_group
                    is_group: true
                    children:
                        # 网校信息
                        admin_v2_school_information_setting:
                            quick_entrance_icon: 'info'
                            name: admin_v2.system.site_menu
                            router_name: admin_v2_school_information
                            children:
                                admin_v2_school_information:
                                    name: admin_v2.system.site.basic_tab
                                    router_name: admin_v2_school_information
                                    disable: true
                # 系统管理
                admin_v2_system_group:
                    name: admin_v2.system.basic_group
                    is_group: true
                    children:
                        # 系统优化
                        admin_v2_optimize:
                            name: admin_v2.system.optimize_menu
                            children:
                                admin_v2_optimize_settings:
                                    name: admin_v2.system.optimize.basic_tab
                                    disable: true
                                    router_name: admin_v2_optimize
                        admin_v2_roles:
                            name: admin_v2.system.roles_menu
                            children:
                                admin_v2_role_manage:
                                    name: admin_v2.system.roles.basic_tab
                                    disable: true
                                    router_name: admin_v2_roles
                                    children:
                                        admin_v2_role_create:
                                            name: admin_v2.system.roles.basic.create_btn
                                            mode: modal
                                            group: topBtn
                                        admin_v2_role_edit:
                                            name: admin_v2.system.roles.basic.edit_btn
                                            mode: modal
                                            group: groupBtn
                                            router_params:
                                                id: (role.id)
                                        admin_v2_role_delete:
                                            name: admin_v2.system.roles.basic.delete_submit_btn
                                            class: role-delete js-delete-role
                                            group: groupBtn
                                            mode: none
                                            router_params:
                                                id: (role.id)
                        # 系统自检
                        admin_v2_report_status:
                            name: admin_v2.system.report_status_menu
                            children:
                                admin_v2_report_status_list:
                                    name: admin_v2.system.report_status.basic_tab
                                    disable: true
                                    router_name: admin_v2_report_status
                        # 系统日志
                        admin_v2_logs:
                            name: admin_v2.system.logs_menu
                            children:
                                admin_v2_logs_query:
                                    name: admin_v2.system.logs.logs_query_tab
                                    disable: true
                                    router_name: admin_v2_logs
                                admin_v2_logs_prod:
                                    name: admin_v2.system.logs.logs_prod_tab
                                    disable: true
        admin_v2_homepage:
            name: 首页配置
            children:
                admin_v2_homepage_setting:
                    name: 首页配置
                    is_group: true
                    children:
                        admin_v2_homepage_tab:
                            name: 顶部导航设置
                            router_name: admin_v2_homepage_tab_manage
                            children:
                                admin_v2_homepage_tab_manage:
                                    name: admin_v2.system.site.basic_tab
                                    router_name: admin_v2_homepage_tab_manage
                                    disable: true
                        admin_v2_homepage_swiper:
                            name: 首页轮播图设置
                            router_name: admin_v2_homepage_swiper_manage
                            children:
                                admin_v2_homepage_swiper_manage:
                                    name: admin_v2.system.site.basic_tab
                                    router_name: admin_v2_homepage_swiper_manage
                                    disable: true
